export const GET_WORLD_REQUEST = "GET_WORLD_REQUEST";
export const GET_WORLD_SUCCESS = "GET_WORLD_SUCCESS";
export const GET_WORLD_FAIL = "GET_WORLD_FAIL";

export const CREATE_WORLD_SUCCESS = "CREATE_WORLD_SUCCESS";
export const CREATE_WORLD_FAIL = "CREATE_WORLD_FAIL";

export const EVENT_REQUEST = "EVENT_REQUEST";
export const EVENT_SUCCESS = "EVENT_SUCCESS";
export const EVENT_FAIL = "EVENT_FAIL";

export const UPDATE_WORLD = "UPDATE_WORLD";
